name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.3.0
            
    - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20
      uses: docker/login-action@v3.1.0
      with:
    # Server address of Docker registry. If not set then will default to Docker Hub
        
        username: toskka
        # Password or personal access token used to log against the Docker registry
        password: # optional
        # Specifies whether the given registry is ECR (auto, true or false)
          
