name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3.3.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: programa
            
    - name: Docker Login
      uses: docker/login-action@v3.1.0
      with:
        username: toskka
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: toskka/go_ci:${{github.ref_name}}
              
